"""add users table

Revision ID: a7a4b067c4ee
Revises: 2e74c9417fe0
Create Date: 2026-07-21 12:45:10.621594

Also adds the users.id FK to conversations.user_id and
idempotency_keys.user_id, backfilling a placeholder user for any
pre-existing user_id value first — see the comments in upgrade() below.
Generated as one migration (not the two originally planned) because
autogenerate produced both diffs together against a DB that had never seen
an intermediate "users table, no FK yet" state.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7a4b067c4ee"
down_revision: str | Sequence[str] | None = "2e74c9417fe0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("token_limit", sa.Integer(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)

    # WHY hand-added, not autogenerated: `conversations.user_id` and
    # `idempotency_keys.user_id` predate this migration and were always
    # unconstrained (see their models' now-removed "no FK yet" comments) —
    # any row already written under the old MVP auth stub (every one of them
    # is literally "user_dev", or a test-only literal like "some_other_user")
    # has no matching `users` row yet. Backfilling one placeholder user per
    # distinct pre-existing value, before the FK constraints below are
    # added, means this migration is non-destructive on a dev DB that
    # already has data — the alternative (truncating conversations/messages
    # first) would work too but throws away real local history for no
    # reason a backfill can't avoid. `UNION` (not `UNION ALL`) dedupes a
    # user_id appearing in both tables into a single insert.
    op.execute(
        """
        INSERT INTO users (id, email, hashed_password, is_active, is_superuser, is_verified,
                            token_limit, tokens_used)
        SELECT DISTINCT user_id, user_id || '@backfilled.invalid',
               'unusable-backfilled-placeholder-hash', true, false, true, 1000000, 0
        FROM conversations WHERE user_id NOT IN (SELECT id FROM users)
        UNION
        SELECT DISTINCT user_id, user_id || '@backfilled.invalid',
               'unusable-backfilled-placeholder-hash', true, false, true, 1000000, 0
        FROM idempotency_keys WHERE user_id NOT IN (SELECT id FROM users)
        """
    )

    # WHY explicit constraint names, unlike this repo's other migrations:
    # autogenerate emitted `op.create_foreign_key(None, ...)` here (`None` ->
    # database-chosen name) because these two tables predate having a
    # `users` table to reference — every other FK in this codebase
    # (messages.conversation_id) was named by Postgres at CREATE TABLE time
    # instead, which never needs a name in `downgrade()`. Adding a FK to an
    # *existing* table has no such luxury: `downgrade()` must name the
    # constraint it's dropping, or `DROP CONSTRAINT None` fails outright.
    op.create_foreign_key(
        "fk_conversations_user_id_users", "conversations", "users", ["user_id"], ["id"]
    )
    op.create_foreign_key(
        "fk_idempotency_keys_user_id_users", "idempotency_keys", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_idempotency_keys_user_id_users", "idempotency_keys", type_="foreignkey")
    op.drop_constraint("fk_conversations_user_id_users", "conversations", type_="foreignkey")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
